-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 15:06:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema radiobases
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema radiobases
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `radiobases` DEFAULT CHARACTER SET utf8 ;
USE `radiobases` ;

-- -----------------------------------------------------
-- Table `radiobases`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`estado` (
  `idestado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `activo` INT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`municipio` (
  `idmunicipio` INT NOT NULL,
  `nombre` VARCHAR(80) NULL,
  `activo` INT NULL,
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`, `estado_idestado`),
  INDEX `fk_municipio_estado_idx` (`estado_idestado` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_estado`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `radiobases`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`colonia` (
  `idcolonia` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `activo` INT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  PRIMARY KEY (`idcolonia`, `municipio_idmunicipio`),
  INDEX `fk_colonia_municipio1_idx` (`municipio_idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_colonia_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `radiobases`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`torre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`torre` (
  `idtorre` INT NOT NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  PRIMARY KEY (`idtorre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`compania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`compania` (
  `idcompania` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`idcompania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`cobertura` (
  `idcobertura` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `activo` INT NULL,
  PRIMARY KEY (`idcobertura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`antena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`antena` (
  `idantena` INT NOT NULL,
  `compania_idcompania` INT NOT NULL,
  `eci` VARCHAR(45) NULL,
  `enbi` VARCHAR(45) NULL,
  `tac` VARCHAR(45) NULL,
  `pci` VARCHAR(45) NULL,
  `clid` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `cobertura_idcobertura` INT NOT NULL,
  PRIMARY KEY (`idantena`, `compania_idcompania`, `cobertura_idcobertura`),
  INDEX `fk_informacion_compania1_idx` (`compania_idcompania` ASC) VISIBLE,
  INDEX `fk_antena_cobertura1_idx` (`cobertura_idcobertura` ASC) VISIBLE,
  CONSTRAINT `fk_informacion_compania1`
    FOREIGN KEY (`compania_idcompania`)
    REFERENCES `radiobases`.`compania` (`idcompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_antena_cobertura1`
    FOREIGN KEY (`cobertura_idcobertura`)
    REFERENCES `radiobases`.`cobertura` (`idcobertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`fotografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`fotografia` (
  `idfotografia` INT NOT NULL,
  `ruta` VARCHAR(200) NULL,
  `activo` INT NULL,
  `torre_idtorre` INT NOT NULL,
  PRIMARY KEY (`idfotografia`, `torre_idtorre`),
  INDEX `fk_fotografia_torre1_idx` (`torre_idtorre` ASC) VISIBLE,
  CONSTRAINT `fk_fotografia_torre1`
    FOREIGN KEY (`torre_idtorre`)
    REFERENCES `radiobases`.`torre` (`idtorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`poligono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`poligono` (
  `idpoligono` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `coordenadas` TEXT(500) NULL,
  `etiqueta` VARCHAR(100) NULL,
  `tooltip` VARCHAR(100) NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`idpoligono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`colonia_has_torre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`colonia_has_torre` (
  `colonia_idcolonia` INT NOT NULL,
  `torre_idtorre` INT NOT NULL,
  PRIMARY KEY (`colonia_idcolonia`, `torre_idtorre`),
  INDEX `fk_colonia_has_torre_torre1_idx` (`torre_idtorre` ASC) VISIBLE,
  INDEX `fk_colonia_has_torre_colonia1_idx` (`colonia_idcolonia` ASC) VISIBLE,
  CONSTRAINT `fk_colonia_has_torre_colonia1`
    FOREIGN KEY (`colonia_idcolonia`)
    REFERENCES `radiobases`.`colonia` (`idcolonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colonia_has_torre_torre1`
    FOREIGN KEY (`torre_idtorre`)
    REFERENCES `radiobases`.`torre` (`idtorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`torre_has_poligono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`torre_has_poligono` (
  `torre_idtorre` INT NOT NULL,
  `poligono_idpoligono` INT NOT NULL,
  PRIMARY KEY (`torre_idtorre`, `poligono_idpoligono`),
  INDEX `fk_torre_has_poligono_poligono1_idx` (`poligono_idpoligono` ASC) VISIBLE,
  INDEX `fk_torre_has_poligono_torre1_idx` (`torre_idtorre` ASC) VISIBLE,
  CONSTRAINT `fk_torre_has_poligono_torre1`
    FOREIGN KEY (`torre_idtorre`)
    REFERENCES `radiobases`.`torre` (`idtorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torre_has_poligono_poligono1`
    FOREIGN KEY (`poligono_idpoligono`)
    REFERENCES `radiobases`.`poligono` (`idpoligono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiobases`.`torre_has_antena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiobases`.`torre_has_antena` (
  `torre_idtorre` INT NOT NULL,
  `antena_idantena` INT NOT NULL,
  PRIMARY KEY (`torre_idtorre`, `antena_idantena`),
  INDEX `fk_torre_has_antena_antena1_idx` (`antena_idantena` ASC) VISIBLE,
  INDEX `fk_torre_has_antena_torre1_idx` (`torre_idtorre` ASC) VISIBLE,
  CONSTRAINT `fk_torre_has_antena_torre1`
    FOREIGN KEY (`torre_idtorre`)
    REFERENCES `radiobases`.`torre` (`idtorre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torre_has_antena_antena1`
    FOREIGN KEY (`antena_idantena`)
    REFERENCES `radiobases`.`antena` (`idantena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
